spring:
  datasource:
    master:
      hikari:
        username: postgres
        password: 12345678
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://masterhost:5432/postgres
    slave1:
      hikari:
        username: postgres
        password: 12345678
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://slave1host:5432/postgres
    slave2:
      hikari:
        username: postgres
        password: 12345678
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://slave2host:5432/postgres

  output:
    ansi:
      enabled: always

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

NUMBER_OF_DB_INSTANCE: 2